### ISSUE TITLE
BlockWatcher encounters an error when running against Ganache

### ISSUE THREAD

**Issue by albrow** [0xProject/0x-mesh#215] opened 2019-07-08 23:49 UTC
I'm seeing the following error message show up a lot when running Mesh locally with Ganache as the Ethereum node:

```json
{
  "error": "Post http://localhost:8545: EOF",
  "level": "error",
  "msg": "BlockWatcher error encountered",
  "time": "2019-07-08T16:47:27-07:00"
}
```

@fabioberger any ideas?

**Comment by fabioberger** [comment] 2019-07-09 12:29
I did some digging and found out that it's because the `go-ethereum` RPC client we're using to send the `eth_getBlockByNumber` JSON RPC request is instructing Ganache to keep the connection alive, but it is ignore this instruction and closing it after responding to each request. The client then tries to re-use the connection and receives an `EOF` response.

I was able to fix this issue by adding `req.Close = true` to the HTTP rpc client code in `go-ethereum`, which instructs the client to close the connection after each request. There doesn't seem to be a way to configure this behavior via the client's public interface unfortunately. 

We have several options on how to proceed:
1. Open an issue/PR with Ganache to respect the `Connection: Keep-Alive` header in requests.
2. Open a PR with `go-ethereum` to optionally configure whether the connections should be kept alive.
3. Stop using the `go-ethereum` RPC client for this request and instead craft the request ourselves such that it closes the connection after each request is sent. 

I'd be in favor of doing (3) as a stop-gap solution, and also doing (1) since this behavior by Ganache is different from that of other Ethereum nodes, and it would be better if we could standardize their behavior.

**Comment by albrow** [comment] 2019-07-09 17:42
@fabioberger thank you for digging into this. My vote would be to open an issue with Ganache and then stop worrying about it for now. The error seems to only happen with Ganache and even then it doesn't cause any real problems (seems we eventually retry the request?).

**Comment by fabioberger** [comment] 2019-07-09 17:52
Sounds good. Will open an issue. Let's keep this one open as well until it's resolved.

**Comment by robert-e-davidson3** [comment] 2019-11-18 19:41
What's the issue number? This is interfering with our local testing.

**Comment by albrow** [comment] 2019-11-18 22:35
@robert-e-davidson3 can you clarify exactly how this issue is affecting you? We run lots of tests against Ganache in CI and while we do see occasional `EOF` errors in the logs during our tests, it doesn't seem to break anything.

**Comment by robert-e-davidson3** [comment] 2019-11-19 00:12
I'm getting connection refused errors now so I can't repro. It's likely that I was misidentifying the cause of the problem I was seeing, now that I know the EOF errors weren't meaningful.

**Comment by albrow** [comment] 2019-11-19 00:22
@robert-e-davidson3 Got it. Keep us updated and feel free to reach out here or on Discord if anything else comes up.

**Comment by fabioberger** [comment] 2019-11-20 16:34
Just wanted to confirm that this error message does not impact the proper operation of the Mesh node. It is an error from which it gracefully recovers.

That being said, it can be made to happen less frequently by setting the `keepAliveTimeout` config on [Ganache-cli](https://github.com/trufflesuite/ganache-cli#options-1) to a larger number then it's default `5000` (5sec). Per the [Node.js docs](https://nodejs.org/api/http.html#http_server_keepalivetimeout) this flag configures:


> The number of milliseconds of inactivity a server needs to wait for additional incoming data, after  it has finished writing the last response, before a socket will be destroyed. If the server receives  new data before the keep-alive timeout has fired, it will reset the regular inactivity timeout, i.e.,  server.timeout.

The `go-ethereum` `rpc` package's [http client](https://github.com/ethereum/go-ethereum/blob/master/rpc/http.go#L169) re-uses TCP connections between requests (the default behavior for the `net/http` package) and this error occurs when it attempts to re-use a TCP connection that has been closed by the server.

By setting `keepAliveTimeout` to a higher amount, say `40000` (40sec) the errors no longer happen.

**Closed** 2019-11-21 23:16 UTC
Labels: bug
