### ISSUE TITLE
db: transaction race-condition

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#220] opened 2019-07-10 12:52 UTC
Saw this on CI today:

```
#!/bin/bash -eo pipefail
make test-go

go test ./... -race
?   	github.com/0xProject/0x-mesh/cmd/demo/add_order	[no test files]
?   	github.com/0xProject/0x-mesh/cmd/demo/add_peer	[no test files]
?   	github.com/0xProject/0x-mesh/cmd/demo/subscribe_to_orders	[no test files]
?   	github.com/0xProject/0x-mesh/cmd/mesh	[no test files]
?   	github.com/0xProject/0x-mesh/cmd/mesh-keygen	[no test files]
?   	github.com/0xProject/0x-mesh/constants	[no test files]
ok  	github.com/0xProject/0x-mesh/core	1.052s
--- FAIL: TestGlobalTransaction (0.01s)
    global_transaction_test.go:111: new collection was created before the transaction was committed
FAIL
FAIL	github.com/0xProject/0x-mesh/db	0.195s
ok  	github.com/0xProject/0x-mesh/ethereum	1.261s
ok  	github.com/0xProject/0x-mesh/ethereum/blockwatch	1.421s
?   	github.com/0xProject/0x-mesh/ethereum/wrappers	[no test files]
ok  	github.com/0xProject/0x-mesh/expirationwatch	1.074s
?   	github.com/0xProject/0x-mesh/keys	[no test files]
ok  	github.com/0xProject/0x-mesh/meshdb	1.089s
ok  	github.com/0xProject/0x-mesh/p2p	4.805s
ok  	github.com/0xProject/0x-mesh/rpc	1.125s
ok  	github.com/0xProject/0x-mesh/zeroex	2.139s
ok  	github.com/0xProject/0x-mesh/zeroex/orderwatch	1.114s
Makefile:36: recipe for target 'test-go' failed
make: *** [test-go] Error 1
Exited with code 2
```

**Comment by albrow** [comment] 2019-07-10 19:43
I ran the test locally about 25 times and wasn't able to reproduce. I'm not sure what could be causing this, but I can provide some additional information about what exactly is going on.

The expected behavior is that no new collections should be created while a `GlobalTransaction` is open. We enforce this constraint with [a mutex called `colLock`](https://github.com/0xProject/0x-mesh/blob/71f2326d2fed13f8e1605eef405799a243ad924c/db/db.go#L36) which is part of the `db.DB` struct type.

When a new global transaction is opened by calling `db.OpenGlobalTransaction`, we [acquire a lock on `colLock`](https://github.com/0xProject/0x-mesh/blob/71f2326d2fed13f8e1605eef405799a243ad924c/db/global_transaction.go#L48). We don't unlock it until the transaction is [committed](https://github.com/0xProject/0x-mesh/blob/71f2326d2fed13f8e1605eef405799a243ad924c/db/global_transaction.go#L100) or [discarded](https://github.com/0xProject/0x-mesh/blob/71f2326d2fed13f8e1605eef405799a243ad924c/db/global_transaction.go#L119).

We also [acquire a lock on `colLock`](https://github.com/0xProject/0x-mesh/blob/71f2326d2fed13f8e1605eef405799a243ad924c/db/collection.go#L22`, ) when a new collection is created by calling `db.NewCollection`, the lock must be acquired before the function returns. It seems pretty straightforward. `db.NewCollection` cannot return until after the `GlobalTransaction` releases the lock on `colLock`.

Maybe the bug lies in the test code and not in the code we are trying to test?  The test that is failing is called [`GlobalTransactionTest`](https://github.com/0xProject/0x-mesh/blob/71f2326d2fed13f8e1605eef405799a243ad924c/db/global_transaction_test.go#L13) and the [exact line it fails on is 111](https://github.com/0xProject/0x-mesh/blob/71f2326d2fed13f8e1605eef405799a243ad924c/db/global_transaction_test.go#L111):

```go
wg.Add(1)
go func() {
	defer wg.Done()
	select {
	case <-commitSignal:
		// Expected outcome. Return from goroutine.
		return
	case <-newCollectionSignal:
		// Not the expected outcome. commitSignal should have fired first.
		t.Error("new collection was created before the transaction was committed")
		return
	}
}()
```

We use two channels and a select statement to determine the order in which events happen. The `commitSignal` channel is expected to fire first. Here's [the code that fires `commitSignal`](https://github.com/0xProject/0x-mesh/blob/71f2326d2fed13f8e1605eef405799a243ad924c/db/global_transaction_test.go#L137):

```go
// Signal that we are about to commit the transaction, then commit it.
commitSignal <- struct{}{}
require.NoError(t, txn.Commit())
```

Note that we fire the signal *right before* committing the transaction. This is because by the time `txn.Commit` returns, `colLock` will have already been unlocked.

The `newCollectionSignal` is expected to fire second (and therefore won't actually be received because the goroutine that would receive it will have exited). Here's [the code that fires `newCollectionSignal`](https://github.com/0xProject/0x-mesh/blob/71f2326d2fed13f8e1605eef405799a243ad924c/db/global_transaction_test.go#L116):

``` go
wg.Add(1)
go func() {
	defer wg.Done()
	_, err := db.NewCollection("people2", &testModel{})
	require.NoError(t, err)
	// Signal that the new collection was created.
	newCollectionSignal <- struct{}{}
}()
```

Note that this is fired *after* `db.NewCollection` returns.

I must be missing something. I can't find any explanation for the behavior we're seeing in CI.

**Closed** 2019-07-10 20:39 UTC
Labels: bug
