### ISSUE TITLE
ETH RPC Requests too many in 24 hr period

### ISSUE THREAD

**Issue by joeykrug** [0xProject/0x-mesh#628] opened 2020-01-07 19:01 UTC
https://cdn.discordapp.com/attachments/378030793899114516/664160069390303262/unknown.png

```
git clone https://github.com/AugurProject/augur.git
yarn clean
 yarn 
yarn build
 yarn docker:all true  
yarn build -w
 yarn workspace @augurproject/ui dev
  yarn flash run create-reasonable-yes-no-market
```

**Comment by albrow** [comment] 2020-01-07 19:15
@joeykrug does this only happen sometimes or does it happen every time? Is it happening for everyone on your team or just some people?

**Comment by albrow** [comment] 2020-01-07 19:43
I can't reproduce this. I followed all the steps above and opened http://localhost:808/ in my browser. The `ETH RPC Requests too many in 24 hr period` error did not occur. Mesh also logs every 5 minutes how many ETH RPC requests it has sent in the past 24 hours. Here's what I see:

```javascript
{
	"ethRPCRateLimitExpiredRequests_number": 0,
	"ethRPCRequestsSentInCurrentUTCDay_number": 109
	// ...
}
```

This indicates that Mesh sent 109 Ethereum RPC requests in the first 5 minutes, which doesn't seem out of the ordinary to me.

Keep in mind that Mesh stores the total number of RPC requests that have been sent every 24 hours in the database. So if you were sending a lot of requests in an older browser session, Mesh would remember that and it would affect your total request count. Is it possible that someone was doing load testing (i.e. adding many orders over a short period of time) and that is what caused you to exceed the limit?

Otherwise, is there any other information you can give me about the activity leading up to this error? Were you doing anything else besides running the above commands?

**Comment by bthaile** [comment] 2020-01-07 20:50
I've seen this once. I didn't do any load testing or heavy order creation. I'll comment again if I see it pop up.

**Comment by albrow** [comment] 2020-02-05 21:41
@bthaile @joeykrug Are you still experiencing this problem or can we close the issue?

**Comment by bthaile** [comment] 2020-02-05 21:47
I’ve not been seeing this issue anymore. Can close if we see it, we can reopen

**Closed** 2020-02-05 21:58 UTC
Labels: needs more info
